host0:
	@for i in $$(seq 0 9); do \
		go run main.go $$i & \
	done;

host1:
	@for i in $$(seq 10 19); do \
		go run main.go $$i & \
	done;

host2:
	@for i in $$(seq 20 29); do \
		go run main.go $$i & \
	done;

host3:
	@for i in $$(seq 30 39); do \
		go run main.go $$i & \
	done;

host4:
	@for i in $$(seq 40 49); do \
		go run main.go $$i & \
	done;
